fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix: /blog

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /test
